### 목표 설정
- 논리게이트 문제를 해결해보자
- 머신러닝 모델 활용해서 and / xor 연산을 진행해보자
- 0은 false, 1은 true

In [1]:
# 필요한 라이브러리 불러오기
import pandas as pd

In [34]:
# and 연산 모델 만들기
# 1. 데이터셋 구성
and_dict = {      'A' : [0, 1, 0, 1, 0, 0, 1, 0 ],
                  'B' : [1, 1, 1, 0, 1, 0, 1, 1 ],
            'A and B' : [0, 1, 0, 0, 0, 0, 1, 0] }
and_dict

{'A': [0, 1, 0, 1, 0, 0, 1, 0],
 'B': [1, 1, 1, 0, 1, 0, 1, 1],
 'A and B': [0, 1, 0, 0, 0, 0, 1, 0]}

In [35]:
# 데이터프레임으로 만들어주기
and_df = pd.DataFrame(and_dict)
and_df

   A  B  A and B
0  0  1        0
1  1  1        1
2  0  1        0
3  1  0        0
4  0  1        0
5  0  0        0
6  1  1        1
7  0  1        0

In [36]:
# iloc를 활용해서 데이터 분할하기
X_train = and_df.iloc[ 0:6 , 0:2 ]
X_test = and_df.iloc[ 6:8 , 0:2]
y_train = and_df.iloc[ 0:6 , 2 ]
y_test = and_df.iloc[ 6:8 , 2]

In [37]:
X_train

   A  B
0  0  1
1  1  1
2  0  1
3  1  0
4  0  1
5  0  0

In [38]:
X_test

   A  B
6  1  1
7  0  1

In [39]:
y_train

0    0
1    1
2    0
3    0
4    0
5    0
Name: A and B, dtype: int64

In [40]:
y_test

6    1
7    0
Name: A and B, dtype: int64

In [12]:
# 머신러닝 모델 불러오기
from sklearn.neighbors import KNeighborsClassifier

In [13]:
# 모델 객체 생성
# n_neighbors=1 주변 이웃값을 1개만 놓고 보겠다.
and_knn = KNeighborsClassifier(n_neighbors=1)

In [14]:
# 모델 학습
and_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [15]:
# 예측값 확인해보기
pre = and_knn.predict(X_test)
pre

array([1, 0])

In [16]:
# 예측값으로 모델 성능 평가하기
from sklearn.metrics import accuracy_score

In [17]:
# accaccuracy_score() : 정확도 측정도구
# 평가
accuracy_score(y_test, pre)
# aaccuracy_score() 범위값 0.0 ~ 1.0
# 0.0 = 0% / 1.0 = 100%

1.0

In [18]:
# 실습
# XOR 문제 풀어보기
xor_dict = {      'A' : [0, 1, 0, 1, 0, 0, 1, 0 ],
                  'B' : [1, 1, 0, 0, 0, 1, 0, 0 ],
            'A and B' : [1, 0, 0, 1, 0, 1, 1, 0 ], }
xor_dict

{'A': [0, 1, 0, 1, 0, 0, 1, 0],
 'B': [1, 1, 0, 0, 0, 1, 0, 0],
 'A and B': [1, 0, 0, 1, 0, 1, 1, 0]}

In [19]:
# 데이터프레임 만들어주기
xor_df = pd.DataFrame(xor_dict)
xor_df

   A  B  A and B
0  0  1        1
1  1  1        0
2  0  0        0
3  1  0        1
4  0  0        0
5  0  1        1
6  1  0        1
7  0  0        0

In [23]:
# 데이터분할하기
X_train = xor_df.iloc[0:6 , 0:2]
y_train = xor_df.iloc[0:6 , 2]
X_test = xor_df.iloc[6:8 , 0:2]
y_test = xor_df.iloc[6:8 , 2]

In [24]:
X_train

   A  B
0  0  1
1  1  1
2  0  0
3  1  0
4  0  0
5  0  1

In [25]:
X_test

   A  B
6  1  0
7  0  0

In [26]:
y_train

0    1
1    0
2    0
3    1
4    0
5    1
Name: A and B, dtype: int64

In [27]:
y_test

6    1
7    0
Name: A and B, dtype: int64

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
# 모델 객체 생성
# n_neighbors=1 주변 이웃값을 1개만 놓고 보겠다.
xor_knn = KNeighborsClassifier(n_neighbors=1)

In [30]:
# 모델 학습
xor_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [31]:
# 예측값 확인해보기
pre = xor_knn.predict(X_test)
pre

array([1, 0])

In [32]:
# 예측값으로 모델 성능 평가하기
from sklearn.metrics import accuracy_score

In [33]:
# accaccuracy_score() : 정확도 측정도구
# 평가
accuracy_score(y_test, pre)
# aaccuracy_score() 범위값 0.0 ~ 1.0
# 0.0 = 0% / 1.0 = 100%

1.0